import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextAuth.js Example Sign-in Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <Link passHref href="/auth/signin">
            <a className={styles.card}>
              <h2>NextAuth.js Signin</h2>
              <p>Visit custom sign-in page</p>
            </a>
          </Link>
          <a className={styles.card} href="https://next-auth.js.org" rel="noreferrer" target="_blank">
            <h2>NextAuth.js Docs</h2>
            <p>next-auth documentation</p>
          </a>
          <a className={styles.card} href="https://nextjs.org/docs" rel="noreferrer" target="_blank">
            <h2>Next.js Docs</h2>
            <p>next documentation</p>
          </a>
          <a className={styles.card} href="https://github.com/nextauthjs/next-auth" rel="noreferrer" target="_blank">
            <h2>NextAuth.js Repo</h2>
            <p>next-auth repository</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
